// Mirrors backend PermissionCodes (accesscontrol.security.PermissionCodes)
export const PermissionCodes = {
  CREATE_USER: "CREATE_USER",
  VIEW_USERS: "VIEW_USERS",
  UPDATE_USER: "UPDATE_USER",
  DEACTIVATE_USER: "DEACTIVATE_USER",
  RESET_USER_PASSWORD: "RESET_USER_PASSWORD",

  VIEW_ROLES: "VIEW_ROLES",
  MANAGE_ROLE_PERMISSIONS: "MANAGE_ROLE_PERMISSIONS",

  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",

  CONFIGURE_MFA: "CONFIGURE_MFA",
  CONFIGURE_SESSION_SETTINGS: "CONFIGURE_SESSION_SETTINGS",

  VIEW_BACKUP_STATUS: "VIEW_BACKUP_STATUS",
  TRIGGER_MANUAL_BACKUP: "TRIGGER_MANUAL_BACKUP",

  VIEW_ANALYTICS: "VIEW_ANALYTICS",

  MANAGE_BOOKINGS: "MANAGE_BOOKINGS",
  MANAGE_FLEET: "MANAGE_FLEET",
  MANAGE_PAYMENTS: "MANAGE_PAYMENTS",
  VIEW_OWN_BOOKINGS: "VIEW_OWN_BOOKINGS",

  INSPECT_VEHICLE: "INSPECT_VEHICLE",

  VIEW_SUPPORT_TICKETS: "VIEW_SUPPORT_TICKETS",
  MANAGE_SUPPORT_TICKETS: "MANAGE_SUPPORT_TICKETS",

  MANAGE_DISCOUNTS: "MANAGE_DISCOUNTS",
};

export const RoleNames = [
  "CUSTOMER",
  "JUNIOR_EMPLOYEE",
  "SENIOR_EMPLOYEE",
  "SUPERVISOR",
  "MANAGER",
  "IT_SECURITY",
  "SYSTEM_ADMIN",
];
